/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as R40MinuteTimerRouteImport } from './routes/40-minute-timer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Timer40MinutesRouteImport } from './routes/timer/40-minutes'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R40MinuteTimerRoute = R40MinuteTimerRouteImport.update({
  id: '/40-minute-timer',
  path: '/40-minute-timer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Timer40MinutesRoute = Timer40MinutesRouteImport.update({
  id: '/40-minutes',
  path: '/40-minutes',
  getParentRoute: () => TimerRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/40-minute-timer': typeof R40MinuteTimerRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/timer/40-minutes': typeof Timer40MinutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/40-minute-timer': typeof R40MinuteTimerRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/timer/40-minutes': typeof Timer40MinutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/40-minute-timer': typeof R40MinuteTimerRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/timer/40-minutes': typeof Timer40MinutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/40-minute-timer'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/stats'
    | '/terms'
    | '/timer'
    | '/articles/$slug'
    | '/timer/40-minutes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/40-minute-timer'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/stats'
    | '/terms'
    | '/timer'
    | '/articles/$slug'
    | '/timer/40-minutes'
  id:
    | '__root__'
    | '/'
    | '/40-minute-timer'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/stats'
    | '/terms'
    | '/timer'
    | '/articles/$slug'
    | '/timer/40-minutes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R40MinuteTimerRoute: typeof R40MinuteTimerRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  TimerRoute: typeof TimerRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/40-minute-timer': {
      id: '/40-minute-timer'
      path: '/40-minute-timer'
      fullPath: '/40-minute-timer'
      preLoaderRoute: typeof R40MinuteTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer/40-minutes': {
      id: '/timer/40-minutes'
      path: '/40-minutes'
      fullPath: '/timer/40-minutes'
      preLoaderRoute: typeof Timer40MinutesRouteImport
      parentRoute: typeof TimerRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TimerRouteChildren {
  Timer40MinutesRoute: typeof Timer40MinutesRoute
}

const TimerRouteChildren: TimerRouteChildren = {
  Timer40MinutesRoute: Timer40MinutesRoute,
}

const TimerRouteWithChildren = TimerRoute._addFileChildren(TimerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R40MinuteTimerRoute: R40MinuteTimerRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  TimerRoute: TimerRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
